---
root: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    ecmaVersion: 2020
    jsx: true
env:
  browser: true
  node: true
settings:
  react:
    version: detect
plugins:
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - prettier
rules:
  'no-prototype-builtins': off
  'react-hooks/exhaustive-deps': off
  '@typescript-eslint/no-unnecessary-type-constraint': off
  '@typescript-eslint/ban-ts-comment': off
